name: sport_in_books
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  # audioplayers: ^4.1.0
  get: ^4.6.5
  draggable_scrollbar: ^0.1.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/backgrounds/
    - assets/images/books/
    - assets/images/headers/
    - assets/audio/

  fonts:
    - family: FreeSetExtraBoldC
      fonts:
        - asset: assets/fonts/FreeSetExtraBoldC-Regular.otf
          weight: 400